import { chromium } from 'playwright';
import http from 'http'; import fs from 'fs'; import path from 'path';
const root = path.dirname(new URL(import.meta.url).pathname);
const types = { '.html': 'text/html', '.js': 'text/javascript', '.wasm': 'application/wasm', '.glb': 'model/gltf-binary' };
const srv = http.createServer((q, s) => { const p = path.join(root, decodeURIComponent(q.url.split('?')[0])); if (!fs.existsSync(p)) { s.writeHead(404); return s.end(); } s.writeHead(200, { 'content-type': types[path.extname(p)] || 'application/octet-stream' }); fs.createReadStream(p).pipe(s); }).listen(8766);
const P = fs.readFileSync(process.argv[2], 'utf8');
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--headless=new', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const pg = await b.newPage(); pg.on('console', (m) => console.log('LOG', m.text())); pg.on('pageerror', (e) => console.log('ERR', e.message));
await pg.goto('http://localhost:8766/scene.html?p=' + encodeURIComponent(P));
await pg.waitForFunction(() => window.__png, null, { timeout: 180000 });
const png = await pg.evaluate(() => window.__png);
fs.writeFileSync(process.argv[3], Buffer.from(png.split(',')[1], 'base64'));
await b.close(); srv.close();
